#define IMU_EEPROM_OFFSET 0
#define BASE1_EEPROM_OFFSET 16
#define BASE2_EEPROM_OFFSET 20

#define LIFTER1_EEPROM_OFFSET 24
#define LIFTER2_EEPROM_OFFSET 44
#define ROBOT_ID_EEPROM_OFFSET 64
#define ROBOT_HARDWARE_CODE_EPPROM_OFFSET 68

#define ROBOT_ID_VALID_CODE 0xB000
#define ROBOT_HARDWARE_CODE_VALID_CODE 0xA000
